### ISSUE TITLE
chown support

### ISSUE THREAD

**Issue by germgerm** [jerrysu/gulp-rsync#36] opened 2016-05-10 11:16 UTC
Any possibility of getting chown support added ?

**Comment by ebaskoro** [comment] 2016-06-15 02:41
Hi. Sure. We will add this to the next release. Thanks.

**Comment by Preen** [comment] 2016-09-27 12:27
+

**Comment by ebaskoro** [comment] 2017-05-22 02:31
Hi @germgerm this is a dupe of #42. Thanks.

**Closed by ebaskoro** 2017-05-22 02:31 UTC
